import '../chick_feed_requirement_screen/widgets/daybreed_item_widget.dart';import 'bloc/chick_feed_requirement_bloc.dart';import 'models/chick_feed_requirement_model.dart';import 'models/daybreed_item_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/presentation/homepage_service_buy_page/homepage_service_buy_page.dart';import 'package:basri_s_application4/presentation/income_one_page/income_one_page.dart';import 'package:basri_s_application4/presentation/new_order_tab_container_page/new_order_tab_container_page.dart';import 'package:basri_s_application4/presentation/single_batch_view_income_page/single_batch_view_income_page.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_bottom_bar.dart';import 'package:basri_s_application4/widgets/custom_floating_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class ChickFeedRequirementScreen extends StatelessWidget {ChickFeedRequirementScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<ChickFeedRequirementBloc>(create: (context) => ChickFeedRequirementBloc(ChickFeedRequirementState(chickFeedRequirementModelObj: ChickFeedRequirementModel()))..add(ChickFeedRequirementInitialEvent()), child: ChickFeedRequirementScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 12.v), _buildChickFeedRequirement(context), Spacer()])), bottomNavigationBar: _buildBottomBar(context), floatingActionButton: _buildFloatingActionButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 19.v, bottom: 18.v), onTap: () {onTapArrowOne(context);}), title: AppbarTitle(text: "msg_chick_feed_requirement".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 12.v, 16.h, 21.v))]); } 
/// Section Widget
Widget _buildChickFeedRequirement(BuildContext context) { return Column(children: [Padding(padding: EdgeInsets.only(right: 15.h), child: BlocSelector<ChickFeedRequirementBloc, ChickFeedRequirementState, TextEditingController?>(selector: (state) => state.menuThirtyEightController, builder: (context, menuThirtyEightController) {return CustomTextFormField(width: 117.h, controller: menuThirtyEightController, hintText: "lbl_breed".tr, hintStyle: CustomTextStyles.labelLargeBahnschrift, textInputAction: TextInputAction.done, alignment: Alignment.centerRight, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 8.h, 9.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 11.adaptSize, width: 11.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 30.v), contentPadding: EdgeInsets.only(left: 10.h, top: 7.v, bottom: 7.v));})), SizedBox(height: 24.v), Column(children: [Divider(), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(right: 2.h), child: BlocSelector<ChickFeedRequirementBloc, ChickFeedRequirementState, ChickFeedRequirementModel?>(selector: (state) => state.chickFeedRequirementModelObj, builder: (context, chickFeedRequirementModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 7.0.v), child: SizedBox(width: double.maxFinite, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray300)));}, itemCount: chickFeedRequirementModelObj?.daybreedItemList.length ?? 0, itemBuilder: (context, index) {DaybreedItemModel model = chickFeedRequirementModelObj?.daybreedItemList[index] ?? DaybreedItemModel(); return DaybreedItemWidget(model);});})), SizedBox(height: 5.v), Divider(), Divider()])]); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
/// Section Widget
Widget _buildFloatingActionButton(BuildContext context) { return CustomFloatingButton(height: 60, width: 60, backgroundColor: theme.colorScheme.primary, child: CustomImageView(imagePath: ImageConstant.imgMaterialSymbolsAdd, height: 30.0.v, width: 30.0.h)); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Buysell: return AppRoutes.homepageServiceBuyPage; case BottomBarEnum.Batches: return AppRoutes.singleBatchViewIncomePage; case BottomBarEnum.Feedmanagement: return AppRoutes.newOrderTabContainerPage; case BottomBarEnum.Farmsettings: return AppRoutes.incomeOnePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.homepageServiceBuyPage: return HomepageServiceBuyPage.builder(context); case AppRoutes.singleBatchViewIncomePage: return SingleBatchViewIncomePage.builder(context); case AppRoutes.newOrderTabContainerPage: return NewOrderTabContainerPage.builder(context); case AppRoutes.incomeOnePage: return IncomeOnePage.builder(context); default: return DefaultWidget();} } 
/// Navigates to the farmSettingsScreen when the action is triggered.
onTapArrowOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.farmSettingsScreen, ); } 
 }
