import '../single_batch_view_expense_screen/widgets/userprofile1_item_widget.dart';import 'bloc/single_batch_view_expense_bloc.dart';import 'models/single_batch_view_expense_model.dart';import 'models/userprofile1_item_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/presentation/homepage_service_buy_page/homepage_service_buy_page.dart';import 'package:basri_s_application4/presentation/income_one_page/income_one_page.dart';import 'package:basri_s_application4/presentation/new_order_tab_container_page/new_order_tab_container_page.dart';import 'package:basri_s_application4/presentation/single_batch_view_income_page/single_batch_view_income_page.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_bottom_bar.dart';import 'package:basri_s_application4/widgets/custom_floating_button.dart';import 'package:basri_s_application4/widgets/custom_icon_button.dart';import 'package:basri_s_application4/widgets/custom_search_view.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class SingleBatchViewExpenseScreen extends StatelessWidget {SingleBatchViewExpenseScreen({Key? key}) : super(key: key);

GlobalKey<NavigatorState> navigatorKey = GlobalKey();

static Widget builder(BuildContext context) { return BlocProvider<SingleBatchViewExpenseBloc>(create: (context) => SingleBatchViewExpenseBloc(SingleBatchViewExpenseState(singleBatchViewExpenseModelObj: SingleBatchViewExpenseModel()))..add(SingleBatchViewExpenseInitialEvent()), child: SingleBatchViewExpenseScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 4.v), Column(children: [Text("lbl_expense".tr, style: CustomTextStyles.titleLargePoppinsBlack900SemiBold), SizedBox(height: 6.v), _buildSearchRow(context), SizedBox(height: 26.v), _buildUserProfile(context)])])), bottomNavigationBar: _buildBottomBar(context), floatingActionButton: _buildFloatingActionButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 55.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 16.v), onTap: () {onTapArrowOne(context);}), title: AppbarTitle(text: "lbl_batch".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 19.v))]); } 
/// Section Widget
Widget _buildSearchRow(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: BlocSelector<SingleBatchViewExpenseBloc, SingleBatchViewExpenseState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_search_expenses".tr);})), Padding(padding: EdgeInsets.only(left: 13.h), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(11.h), decoration: IconButtonStyleHelper.outlineIndigoTL6, child: CustomImageView(imagePath: ImageConstant.imgGroup401)))])); } 
/// Section Widget
Widget _buildUserProfile(BuildContext context) { return BlocSelector<SingleBatchViewExpenseBloc, SingleBatchViewExpenseState, SingleBatchViewExpenseModel?>(selector: (state) => state.singleBatchViewExpenseModelObj, builder: (context, singleBatchViewExpenseModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 0.5.v), child: SizedBox(width: double.maxFinite, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray300)));}, itemCount: singleBatchViewExpenseModelObj?.userprofile1ItemList.length ?? 0, itemBuilder: (context, index) {Userprofile1ItemModel model = singleBatchViewExpenseModelObj?.userprofile1ItemList[index] ?? Userprofile1ItemModel(); return Userprofile1ItemWidget(model);});}); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return CustomBottomBar(onChanged: (BottomBarEnum type) {Navigator.pushNamed(navigatorKey.currentContext!, getCurrentRoute(type));}); } 
/// Section Widget
Widget _buildFloatingActionButton(BuildContext context) { return CustomFloatingButton(height: 60, width: 60, backgroundColor: theme.colorScheme.primary, child: CustomImageView(imagePath: ImageConstant.imgMaterialSymbolsAdd, height: 30.0.v, width: 30.0.h)); } 
///Handling route based on bottom click actions
String getCurrentRoute(BottomBarEnum type) { switch (type) {case BottomBarEnum.Buysell: return AppRoutes.homepageServiceBuyPage; case BottomBarEnum.Batches: return AppRoutes.singleBatchViewIncomePage; case BottomBarEnum.Feedmanagement: return AppRoutes.newOrderTabContainerPage; case BottomBarEnum.Farmsettings: return AppRoutes.incomeOnePage; default: return "/";} } 
///Handling page based on route
Widget getCurrentPage(BuildContext context, String currentRoute, ) { switch (currentRoute) {case AppRoutes.homepageServiceBuyPage: return HomepageServiceBuyPage.builder(context); case AppRoutes.singleBatchViewIncomePage: return SingleBatchViewIncomePage.builder(context); case AppRoutes.newOrderTabContainerPage: return NewOrderTabContainerPage.builder(context); case AppRoutes.incomeOnePage: return IncomeOnePage.builder(context); default: return DefaultWidget();} } 
/// Navigates to the singleBatchRecordsTabContainerScreen when the action is triggered.
onTapArrowOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.singleBatchRecordsTabContainerScreen, ); } 
 }
