import 'bloc/logout_bloc.dart';import 'models/logout_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_outlined_button.dart';import 'package:flutter/material.dart';class LogoutDialog extends StatelessWidget {const LogoutDialog({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<LogoutBloc>(create: (context) => LogoutBloc(LogoutState(logoutModelObj: LogoutModel()))..add(LogoutInitialEvent()), child: LogoutDialog()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return Container(width: 314.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 38.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.circleBorder22), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgDoor1, height: 83.adaptSize, width: 83.adaptSize), SizedBox(height: 37.v), Text("msg_are_you_sure_you".tr, style: CustomTextStyles.titleMediumBahnschrift), SizedBox(height: 26.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomOutlinedButton(text: "lbl_cancel".tr, margin: EdgeInsets.only(right: 8.h), buttonStyle: CustomButtonStyles.outlinePrimary, buttonTextStyle: CustomTextStyles.titleMediumBahnschriftBluegray40001Bold, onPressed: () {onTapCancel(context);})), Expanded(child: CustomElevatedButton(height: 40.v, text: "lbl_logout".tr, margin: EdgeInsets.only(left: 8.h), buttonTextStyle: CustomTextStyles.titleMediumBahnschriftOnPrimaryContainerBold, onPressed: () {onTapLogout(context);}))]), SizedBox(height: 3.v)])); } 
/// Navigates to the homepageServiceBuyOneScreen when the action is triggered.
onTapCancel(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homepageServiceBuyOneScreen, ); } 
/// Navigates to the splashScreen when the action is triggered.
onTapLogout(BuildContext context) { NavigatorService.pushNamed(AppRoutes.splashScreen, ); } 
 }
