import 'bloc/single_batch_vaccination_two_bloc.dart';import 'models/single_batch_vaccination_two_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class SingleBatchVaccinationTwoScreen extends StatelessWidget {const SingleBatchVaccinationTwoScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SingleBatchVaccinationTwoBloc>(create: (context) => SingleBatchVaccinationTwoBloc(SingleBatchVaccinationTwoState(singleBatchVaccinationTwoModelObj: SingleBatchVaccinationTwoModel()))..add(SingleBatchVaccinationTwoInitialEvent()), child: SingleBatchVaccinationTwoScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 1.v), child: Column(children: [Text("lbl_add_vaccination".tr, style: CustomTextStyles.titleLargePoppinsBlack900SemiBold), SizedBox(height: 19.v), _buildAddVaccinationDate(context), SizedBox(height: 15.v), _buildAddVaccinationVaccineValue(context), SizedBox(height: 15.v), _buildAddVaccinationVaccineTypeValue(context), SizedBox(height: 15.v), _buildAddVaccinationMethodValue(context), SizedBox(height: 15.v), _buildAddVaccinationDescriptionValue(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildAddButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 18.v, bottom: 16.v), onTap: () {onTapArrowOne(context);}), title: AppbarTitle(text: "lbl_batch".tr, margin: EdgeInsets.only(left: 31.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 17.v))]); } 
/// Section Widget
Widget _buildAddVaccinationDate(BuildContext context) { return BlocSelector<SingleBatchVaccinationTwoBloc, SingleBatchVaccinationTwoState, TextEditingController?>(selector: (state) => state.addVaccinationDateController, builder: (context, addVaccinationDateController) {return CustomTextFormField(controller: addVaccinationDateController, hintText: "lbl_date".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 19.v, 21.h, 19.v), child: CustomImageView(imagePath: ImageConstant.imgVector, height: 18.v, width: 16.h)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildAddVaccinationVaccineValue(BuildContext context) { return BlocSelector<SingleBatchVaccinationTwoBloc, SingleBatchVaccinationTwoState, TextEditingController?>(selector: (state) => state.addVaccinationVaccineValueController, builder: (context, addVaccinationVaccineValueController) {return CustomTextFormField(controller: addVaccinationVaccineValueController, hintText: "lbl_vaccine".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 23.v, 22.h, 20.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildAddVaccinationVaccineTypeValue(BuildContext context) { return BlocSelector<SingleBatchVaccinationTwoBloc, SingleBatchVaccinationTwoState, TextEditingController?>(selector: (state) => state.addVaccinationVaccineTypeValueController, builder: (context, addVaccinationVaccineTypeValueController) {return CustomTextFormField(controller: addVaccinationVaccineTypeValueController, hintText: "lbl_vaccine_type2".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 23.v, 22.h, 19.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildAddVaccinationMethodValue(BuildContext context) { return BlocSelector<SingleBatchVaccinationTwoBloc, SingleBatchVaccinationTwoState, TextEditingController?>(selector: (state) => state.addVaccinationMethodValueController, builder: (context, addVaccinationMethodValueController) {return CustomTextFormField(controller: addVaccinationMethodValueController, hintText: "lbl_method2".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 21.v, 22.h, 22.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildAddVaccinationDescriptionValue(BuildContext context) { return BlocSelector<SingleBatchVaccinationTwoBloc, SingleBatchVaccinationTwoState, TextEditingController?>(selector: (state) => state.addVaccinationDescriptionValueController, builder: (context, addVaccinationDescriptionValueController) {return CustomTextFormField(controller: addVaccinationDescriptionValueController, hintText: "lbl_description2".tr, textInputAction: TextInputAction.done);}); } 
/// Section Widget
Widget _buildAddButton(BuildContext context) { return CustomElevatedButton(text: "lbl_add".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 30.v), onPressed: () {onTapAddButton(context);}); } 
/// Navigates to the singleBatchViewVaccinationOneTabContainerScreen when the action is triggered.
onTapArrowOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.singleBatchViewVaccinationOneTabContainerScreen, ); } 
/// Navigates to the singleBatchViewVaccinationOneTabContainerScreen when the action is triggered.
onTapAddButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.singleBatchViewVaccinationOneTabContainerScreen, ); } 
 }
