import 'bloc/inventory_transfer_five_bloc.dart';import 'models/inventory_transfer_five_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_switch.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class InventoryTransferFiveScreen extends StatelessWidget {const InventoryTransferFiveScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<InventoryTransferFiveBloc>(create: (context) => InventoryTransferFiveBloc(InventoryTransferFiveState(inventoryTransferFiveModelObj: InventoryTransferFiveModel()))..add(InventoryTransferFiveInitialEvent()), child: InventoryTransferFiveScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Row(children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 1.v), child: Text("lbl_stock_in".tr, style: CustomTextStyles.bodyMediumBlack900)), BlocSelector<InventoryTransferFiveBloc, InventoryTransferFiveState, bool?>(selector: (state) => state.isSelectedSwitch, builder: (context, isSelectedSwitch) {return CustomSwitch(margin: EdgeInsets.only(left: 11.h), value: isSelectedSwitch, onChange: (value) {context.read<InventoryTransferFiveBloc>().add(ChangeSwitchEvent(value: value));});}), Padding(padding: EdgeInsets.only(left: 10.h, top: 3.v, bottom: 1.v), child: Text("lbl_stock_out".tr, style: theme.textTheme.bodyMedium))])), SizedBox(height: 22.v), BlocSelector<InventoryTransferFiveBloc, InventoryTransferFiveState, TextEditingController?>(selector: (state) => state.fromBatchController, builder: (context, fromBatchController) {return CustomTextFormField(controller: fromBatchController, hintText: "lbl_from_batch".tr, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 21.v, 22.h, 21.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 58.v), contentPadding: EdgeInsets.only(left: 21.h, top: 19.v, bottom: 19.v));}), SizedBox(height: 15.v), _buildFeedType(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildTransferFeedToInventory(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 19.v, bottom: 18.v)), title: AppbarTitle(text: "msg_transfer_inventory".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 20.v))]); } 
/// Section Widget
Widget _buildFeedType(BuildContext context) { return SizedBox(height: 161.v, width: 358.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(bottom: 102.v), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 17.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("lbl_feed_type".tr, style: theme.textTheme.bodyMedium)), CustomImageView(imagePath: ImageConstant.imgMenu138, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 3.v, right: 1.h, bottom: 2.v), onTap: () {onTapImgMenu(context);})]))), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(bottom: 28.v), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 17.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Text("msg_quantity_stock".tr, style: theme.textTheme.bodyMedium)]))), Align(alignment: Alignment.bottomRight, child: Container(height: 124.v, width: 118.h, margin: EdgeInsets.only(right: 12.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgPolygon1, height: 14.v, width: 24.h, alignment: Alignment.topRight, margin: EdgeInsets.only(right: 7.h)), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_broiler".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 6.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_deshi".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 8.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_layer".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 7.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_breeder_farm".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 1.v)])))])))])); } 
/// Section Widget
Widget _buildTransferFeedToInventory(BuildContext context) { return CustomElevatedButton(text: "msg_transfer_feed_to".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 29.v)); } 
/// Navigates to the inventoryTransferSixScreen when the action is triggered.
onTapImgMenu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.inventoryTransferSixScreen, ); } 
 }
