import 'bloc/inventory_transfer_four_bloc.dart';import 'models/inventory_transfer_four_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_switch.dart';import 'package:flutter/material.dart';class InventoryTransferFourScreen extends StatelessWidget {const InventoryTransferFourScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<InventoryTransferFourBloc>(create: (context) => InventoryTransferFourBloc(InventoryTransferFourState(inventoryTransferFourModelObj: InventoryTransferFourModel()))..add(InventoryTransferFourInitialEvent()), child: InventoryTransferFourScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 1.v), child: Text("lbl_stock_in".tr, style: CustomTextStyles.bodyMediumBlack900)), BlocSelector<InventoryTransferFourBloc, InventoryTransferFourState, bool?>(selector: (state) => state.isSelectedSwitch, builder: (context, isSelectedSwitch) {return CustomSwitch(margin: EdgeInsets.only(left: 11.h), value: isSelectedSwitch, onChange: (value) {context.read<InventoryTransferFourBloc>().add(ChangeSwitchEvent(value: value));});}), Padding(padding: EdgeInsets.only(left: 10.h, top: 3.v, bottom: 1.v), child: Text("lbl_stock_out".tr, style: theme.textTheme.bodyMedium))]), SizedBox(height: 22.v), _buildBatchName(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildTransferFeedToInventory(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 19.v, bottom: 18.v)), title: AppbarTitle(text: "msg_transfer_inventory".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 20.v))]); } 
/// Section Widget
Widget _buildBatchName(BuildContext context) { return SizedBox(height: 206.v, width: 358.h, child: Stack(alignment: Alignment.center, children: [Padding(padding: EdgeInsets.only(bottom: 148.v), child: _buildFeedType(context, feedType: "lbl_from_batch".tr, menuImage: ImageConstant.imgMenu138, onTapMenu: () {onTapMenu(context);})), Padding(padding: EdgeInsets.symmetric(vertical: 73.v), child: _buildFeedType(context, feedType: "lbl_feed_type".tr, menuImage: ImageConstant.imgMenu136)), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 17.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Text("msg_quantity_stock".tr, style: theme.textTheme.bodyMedium)]))), Align(alignment: Alignment.centerRight, child: Container(height: 124.v, width: 118.h, margin: EdgeInsets.only(right: 11.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgPolygon1, height: 14.v, width: 24.h, alignment: Alignment.topRight, margin: EdgeInsets.only(right: 7.h)), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_batch_name".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 6.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_batch_name".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 8.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_batch_name".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 8.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_batch_name".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 1.v)])))])))])); } 
/// Section Widget
Widget _buildTransferFeedToInventory(BuildContext context) { return CustomElevatedButton(text: "msg_transfer_feed_to".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 29.v)); } 
/// Common widget
Widget _buildFeedType(BuildContext context, {required String feedType, required String menuImage, Function? onTapMenu, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 17.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text(feedType, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.blueGray40001))), CustomImageView(imagePath: menuImage, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 3.v, right: 1.h, bottom: 2.v), onTap: () {onTapMenu!.call();})])); } 
/// Navigates to the inventoryTransferSixScreen when the action is triggered.
onTapMenu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.inventoryTransferSixScreen, ); } 
 }
