import 'bloc/register_bloc.dart';import 'models/register_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/core/utils/validation_functions.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class RegisterScreen extends StatelessWidget {RegisterScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<RegisterBloc>(create: (context) => RegisterBloc(RegisterState(registerModelObj: RegisterModel()))..add(RegisterInitialEvent()), child: RegisterScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 20.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Container(width: 292.h, margin: EdgeInsets.only(left: 7.h, right: 60.h), child: Text("msg_hello_register".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineLarge!.copyWith(height: 1.30)))), SizedBox(height: 78.v), BlocSelector<RegisterBloc, RegisterState, TextEditingController?>(selector: (state) => state.userNameController, builder: (context, userNameController) {return CustomTextFormField(controller: userNameController, hintText: "lbl_username".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}), SizedBox(height: 15.v), BlocSelector<RegisterBloc, RegisterState, TextEditingController?>(selector: (state) => state.phoneNumberController, builder: (context, phoneNumberController) {return CustomTextFormField(controller: phoneNumberController, hintText: "lbl_phone_number".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.phone, validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;});}), SizedBox(height: 29.v), CustomElevatedButton(text: "lbl_send_otp".tr, onPressed: () {onTapSendOTP(context);}), SizedBox(height: 47.v), _buildRegisterWith(context), SizedBox(height: 21.v), _buildSocialButtons(context), Spacer(), GestureDetector(onTap: () {onTapTxtAlreadyhavean(context);}, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_already_have_an2".tr, style: CustomTextStyles.bodyMediumOnPrimary), TextSpan(text: "lbl_login_now".tr, style: CustomTextStyles.titleSmallBahnschriftPrimary)]), textAlign: TextAlign.left))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(22.h, 6.v, 325.h, 6.v), onTap: () {onTapArrowLeft(context);})); } 
/// Section Widget
Widget _buildRegisterWith(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: SizedBox(width: 108.h, child: Divider(color: appTheme.indigo50))), Text("msg_or_register_with".tr, style: CustomTextStyles.titleSmallUrbanistGray600), Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: SizedBox(width: 108.h, child: Divider(color: appTheme.indigo50)))])); } 
/// Section Widget
Widget _buildSocialButtons(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 58.v, width: 110.h, padding: EdgeInsets.symmetric(horizontal: 37.h, vertical: 14.v), decoration: AppDecoration.outlineIndigo501.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.imgFacebookIc, height: 27.adaptSize, width: 27.adaptSize, alignment: Alignment.centerLeft)), Container(height: 58.v, width: 110.h, padding: EdgeInsets.symmetric(horizontal: 37.h, vertical: 14.v), decoration: AppDecoration.outlineIndigo501.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.imgGoogleIc, height: 27.adaptSize, width: 27.adaptSize, alignment: Alignment.centerLeft)), Container(height: 58.v, width: 110.h, padding: EdgeInsets.symmetric(horizontal: 37.h, vertical: 14.v), decoration: AppDecoration.outlineIndigo501.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.imgCibApple, height: 27.adaptSize, width: 27.adaptSize, alignment: Alignment.centerLeft))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the otpVerificationOneScreen when the action is triggered.
onTapSendOTP(BuildContext context) { NavigatorService.pushNamed(AppRoutes.otpVerificationOneScreen, ); } 
/// Navigates to the loginScreen when the action is triggered.
onTapTxtAlreadyhavean(BuildContext context) { NavigatorService.pushNamed(AppRoutes.loginScreen, ); } 
 }
