import 'bloc/homepage_sell_one_bloc.dart';import 'models/homepage_sell_one_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class HomepageSellOneScreen extends StatelessWidget {const HomepageSellOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<HomepageSellOneBloc>(create: (context) => HomepageSellOneBloc(HomepageSellOneState(homepageSellOneModelObj: HomepageSellOneModel()))..add(HomepageSellOneInitialEvent()), child: HomepageSellOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<HomepageSellOneBloc, HomepageSellOneState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 16.v), _buildBirdsOne(context), SizedBox(height: 33.v), _buildEggsTwentyOne(context), SizedBox(height: 12.v), _buildHatchingEggs(context), SizedBox(height: 18.v), _buildMeatOne(context), SizedBox(height: 12.v), _buildChickenMeat(context), SizedBox(height: 33.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 16.h), child: Row(children: [Container(height: 105.adaptSize, width: 105.adaptSize, padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 22.v), decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgMedicine1, height: 61.v, width: 81.h, alignment: Alignment.centerLeft)), Container(height: 105.v, width: 103.h, margin: EdgeInsets.only(left: 23.h), padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 23.v), decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgTractorPng16123, height: 58.v, width: 78.h, alignment: Alignment.center))]))), SizedBox(height: 12.v), _buildVaccines(context)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 19.v, bottom: 18.v), onTap: () {onTapArrowOne(context);}), title: AppbarTitle(text: "msg_what_are_you_selling".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 12.v, 16.h, 21.v))]); } 
/// Section Widget
Widget _buildBirdsOne(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [GestureDetector(onTap: () {onTapBirdsOne(context);}, child: Padding(padding: EdgeInsets.only(bottom: 1.v), child: Column(children: [Container(height: 105.adaptSize, width: 105.adaptSize, padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 15.v), decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgBirds1, height: 71.v, width: 77.h, alignment: Alignment.topLeft)), SizedBox(height: 12.v), Text("lbl_broiler".tr, style: CustomTextStyles.bodySmall12)]))), Column(children: [SizedBox(width: 230.h, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 105.v, width: 103.h, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v), decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgCountryHicken700x700, height: 74.adaptSize, width: 74.adaptSize, alignment: Alignment.center)), Container(height: 105.v, width: 103.h, padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 27.v), decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgEggs4, height: 50.v, width: 80.h, alignment: Alignment.center))])), SizedBox(height: 12.v), Container(width: 155.h, margin: EdgeInsets.only(left: 36.h, right: 38.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("lbl_deshi".tr, style: CustomTextStyles.bodySmall12)), Text("lbl_eggs".tr, style: CustomTextStyles.bodySmall12)]))])])); } 
/// Section Widget
Widget _buildEggsTwentyOne(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 105.adaptSize, width: 105.adaptSize, padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 23.v), decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgEggs21, height: 58.v, width: 70.h, alignment: Alignment.center)), Container(height: 105.adaptSize, width: 105.adaptSize, padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 15.v), decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgChick1, height: 73.v, width: 64.h, alignment: Alignment.centerLeft)), SizedBox(height: 105.v, width: 107.h, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.centerLeft, child: Container(height: 105.v, width: 103.h, decoration: BoxDecoration(color: appTheme.indigo50, borderRadius: BorderRadius.circular(15.h)))), CustomImageView(imagePath: ImageConstant.imgPngwing5, height: 66.v, width: 106.h, alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 11.v))]))])); } 
/// Section Widget
Widget _buildHatchingEggs(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 30.h, right: 36.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 14.v), child: Text("lbl_hatching_eggs".tr, style: CustomTextStyles.bodySmall12)), Spacer(flex: 46), Padding(padding: EdgeInsets.only(bottom: 16.v), child: Text("lbl_chicks".tr, style: CustomTextStyles.bodySmall12)), Spacer(flex: 53), SizedBox(width: 63.h, child: Text("msg_machine_equipments".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodySmall12))])); } 
/// Section Widget
Widget _buildMeatOne(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 105.adaptSize, width: 105.adaptSize, padding: EdgeInsets.symmetric(horizontal: 11.h, vertical: 27.v), decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgMeat1, height: 50.v, width: 82.h, alignment: Alignment.center)), Container(height: 105.adaptSize, width: 105.adaptSize, padding: EdgeInsets.symmetric(horizontal: 37.h, vertical: 14.v), decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.img61vwtgcxdgl1, height: 72.v, width: 27.h, alignment: Alignment.topLeft)), Container(height: 105.v, width: 103.h, padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 14.v), decoration: AppDecoration.fillIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder15), child: CustomImageView(imagePath: ImageConstant.imgFeed1, height: 76.v, width: 47.h, alignment: Alignment.center))])); } 
/// Section Widget
Widget _buildChickenMeat(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 33.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_chicken_meat".tr, style: CustomTextStyles.bodySmall12), Padding(padding: EdgeInsets.only(top: 1.v), child: Text("msg_poultry_medicine".tr, style: CustomTextStyles.bodySmall12)), Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_poultry_feed".tr, style: CustomTextStyles.bodySmall12))])); } 
/// Section Widget
Widget _buildVaccines(BuildContext context) { return SizedBox(height: 106.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 42.h), child: Text("lbl_vaccines".tr, style: CustomTextStyles.bodySmall12))), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_transportation".tr, style: CustomTextStyles.bodySmall12))), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 5.v), decoration: AppDecoration.outlineGray300, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 10.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillPrimary, child: CustomImageView(imagePath: ImageConstant.imgNavBuySell)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(9.h), child: CustomImageView(imagePath: ImageConstant.imgNavBatches)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(11.h), child: CustomImageView(imagePath: ImageConstant.imgNavFeedManagement)))), Expanded(child: Padding(padding: EdgeInsets.only(left: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(11.h), child: CustomImageView(imagePath: ImageConstant.imgNavFarmSettings))))])), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 13.h, right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 11.v), child: Text("lbl_buy_sell".tr, style: theme.textTheme.bodySmall)), Spacer(flex: 37), Padding(padding: EdgeInsets.only(bottom: 11.v), child: Text("lbl_batches".tr, style: theme.textTheme.bodySmall)), Spacer(flex: 31), SizedBox(width: 58.h, child: Text("lbl_feed_management".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodySmall!.copyWith(height: 1.10))), Spacer(flex: 31), SizedBox(width: 37.h, child: Text("lbl_farm_settings".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodySmall!.copyWith(height: 1.10)))]))])))])); } 
/// Navigates to the homepageServiceBuyOneScreen when the action is triggered.
onTapArrowOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homepageServiceBuyOneScreen, ); } 
/// Navigates to the homepageSellScreen when the action is triggered.
onTapBirdsOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homepageSellScreen, ); } 
 }
