import 'bloc/otp_verification_one_bloc.dart';import 'models/otp_verification_one_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';import 'package:basri_s_application4/presentation/otp_verification_dialog/otp_verification_dialog.dart';class OtpVerificationOneScreen extends StatelessWidget {const OtpVerificationOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<OtpVerificationOneBloc>(create: (context) => OtpVerificationOneBloc(OtpVerificationOneState(otpVerificationOneModelObj: OtpVerificationOneModel()))..add(OtpVerificationOneInitialEvent()), child: OtpVerificationOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 22.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Text("msg_otp_verification".tr, style: theme.textTheme.headlineLarge))), SizedBox(height: 13.v), Align(alignment: Alignment.centerLeft, child: Container(width: 317.h, margin: EdgeInsets.only(left: 2.h, right: 30.h), child: Text("msg_enter_the_verification".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeBluegray400.copyWith(height: 1.50)))), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 2.h), child: BlocSelector<OtpVerificationOneBloc, OtpVerificationOneState, TextEditingController?>(selector: (state) => state.otpController, builder: (context, otpController) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});})), SizedBox(height: 39.v), CustomElevatedButton(text: "lbl_verify".tr, onPressed: () {onTapVerify(context);}), Spacer(), RichText(text: TextSpan(children: [TextSpan(text: "msg_didn_t_received2".tr, style: CustomTextStyles.bodyMediumOnPrimary), TextSpan(text: "lbl_resend".tr, style: CustomTextStyles.titleSmallBahnschriftPrimary)]), textAlign: TextAlign.left)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(22.h, 6.v, 325.h, 6.v), onTap: () {onTapArrowLeft(context);})); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 

/// Displays a dialog with the [OtpVerificationDialog] content.
onTapVerify(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: OtpVerificationDialog.builder(context),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
 }
