import 'bloc/about_us_bloc.dart';import 'models/about_us_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class AboutUsScreen extends StatelessWidget {const AboutUsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AboutUsBloc>(create: (context) => AboutUsBloc(AboutUsState(aboutUsModelObj: AboutUsModel()))..add(AboutUsInitialEvent()), child: AboutUsScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<AboutUsBloc, AboutUsState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 39.v), CustomImageView(imagePath: ImageConstant.imgImage1, height: 162.adaptSize, width: 162.adaptSize), SizedBox(height: 29.v), Text("msg_happy_poultry_farm".tr, style: CustomTextStyles.titleMediumSemiBold), SizedBox(height: 19.v), Container(width: 356.h, margin: EdgeInsets.only(left: 16.h, right: 17.h), child: Text("msg_welcome_to_happy".tr, maxLines: 20, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallPoppins12)), SizedBox(height: 13.v), _buildHappyPoultryFarmSettings(context)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 55.v, leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 20.v, bottom: 16.v), onTap: () {onTapArrowOne(context);}), title: AppbarTitle(text: "lbl_about_us".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 19.v))]); } 
/// Section Widget
Widget _buildHappyPoultryFarmSettings(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 5.v), decoration: AppDecoration.outlineGray300, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 10.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillPrimary, child: CustomImageView(imagePath: ImageConstant.imgNavBuySell)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(9.h), child: CustomImageView(imagePath: ImageConstant.imgNavBatches)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(11.h), child: CustomImageView(imagePath: ImageConstant.imgNavFeedManagement)))), Expanded(child: Padding(padding: EdgeInsets.only(left: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(11.h), child: CustomImageView(imagePath: ImageConstant.imgNavFarmSettings))))])), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 13.h, right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 11.v), child: Text("lbl_buy_sell".tr, style: theme.textTheme.bodySmall)), Spacer(flex: 37), Padding(padding: EdgeInsets.only(bottom: 11.v), child: Text("lbl_batches".tr, style: theme.textTheme.bodySmall)), Spacer(flex: 31), SizedBox(width: 58.h, child: Text("lbl_feed_management".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodySmall!.copyWith(height: 1.10))), Spacer(flex: 31), SizedBox(width: 37.h, child: Text("lbl_farm_settings".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodySmall!.copyWith(height: 1.10)))]))])); } 
/// Navigates to the homepageServiceBuyOneScreen when the action is triggered.
onTapArrowOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homepageServiceBuyOneScreen, ); } 
 }
