import 'bloc/vaccination_schedule_five_bloc.dart';import 'models/vaccination_schedule_five_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class VaccinationScheduleFiveScreen extends StatelessWidget {const VaccinationScheduleFiveScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<VaccinationScheduleFiveBloc>(create: (context) => VaccinationScheduleFiveBloc(VaccinationScheduleFiveState(vaccinationScheduleFiveModelObj: VaccinationScheduleFiveModel()))..add(VaccinationScheduleFiveInitialEvent()), child: VaccinationScheduleFiveScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 18.v), child: Column(children: [_buildBreedStack(context), SizedBox(height: 15.v), _buildMenuThirtyEight(context), SizedBox(height: 15.v), _buildMenuThirtyNine(context), SizedBox(height: 15.v), _buildDescription(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildAdd(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 54.v, leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 19.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_add_vaccination".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 18.v))]); } 
/// Section Widget
Widget _buildBreedStack(BuildContext context) { return SizedBox(height: 206.v, width: 358.h, child: Stack(alignment: Alignment.center, children: [Padding(padding: EdgeInsets.only(bottom: 148.v), child: _buildVaccine(context, vaccine: "lbl_breed".tr, menuImage: ImageConstant.imgMenu138, onTapMenu: () {onTapMenu(context);})), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 17.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Text("lbl_day".tr, style: theme.textTheme.bodyMedium)]))), Padding(padding: EdgeInsets.only(top: 147.v), child: _buildVaccine(context, vaccine: "lbl_vaccine".tr, menuImage: ImageConstant.imgMenu136)), Align(alignment: Alignment.topRight, child: Container(height: 124.v, width: 118.h, margin: EdgeInsets.only(top: 37.v, right: 11.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgPolygon1, height: 14.v, width: 24.h, alignment: Alignment.topRight, margin: EdgeInsets.only(right: 7.h)), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_broiler".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 6.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_deshi".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 8.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_layer".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 7.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_breeder_farm".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 1.v)])))])))])); } 
/// Section Widget
Widget _buildMenuThirtyEight(BuildContext context) { return BlocSelector<VaccinationScheduleFiveBloc, VaccinationScheduleFiveState, TextEditingController?>(selector: (state) => state.menuThirtyEightController, builder: (context, menuThirtyEightController) {return CustomTextFormField(controller: menuThirtyEightController, hintText: "lbl_vaccine_type2".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 23.v, 22.h, 19.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildMenuThirtyNine(BuildContext context) { return BlocSelector<VaccinationScheduleFiveBloc, VaccinationScheduleFiveState, TextEditingController?>(selector: (state) => state.menuThirtyNineController, builder: (context, menuThirtyNineController) {return CustomTextFormField(controller: menuThirtyNineController, hintText: "lbl_method2".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 22.v, 22.h, 21.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildDescription(BuildContext context) { return BlocSelector<VaccinationScheduleFiveBloc, VaccinationScheduleFiveState, TextEditingController?>(selector: (state) => state.descriptionController, builder: (context, descriptionController) {return CustomTextFormField(controller: descriptionController, hintText: "lbl_description2".tr, textInputAction: TextInputAction.done);}); } 
/// Section Widget
Widget _buildAdd(BuildContext context) { return CustomElevatedButton(text: "lbl_add".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 30.v)); } 
/// Common widget
Widget _buildVaccine(BuildContext context, {required String vaccine, required String menuImage, Function? onTapMenu, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 18.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text(vaccine, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.blueGray40001))), CustomImageView(imagePath: menuImage, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 2.v, right: 1.h), onTap: () {onTapMenu!.call();})])); } 
/// Navigates to the vaccinationScheduleFourScreen when the action is triggered.
onTapMenu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.vaccinationScheduleFourScreen, ); } 
 }
