import 'bloc/create_profile_bloc.dart';import 'models/create_profile_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/core/utils/validation_functions.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'package:basri_s_application4/presentation/edit_profile_dialog/edit_profile_dialog.dart';
// ignore_for_file: must_be_immutable
class CreateProfileScreen extends StatelessWidget {CreateProfileScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<CreateProfileBloc>(create: (context) => CreateProfileBloc(CreateProfileState(createProfileModelObj: CreateProfileModel()))..add(CreateProfileInitialEvent()), child: CreateProfileScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 19.v), child: Column(children: [SizedBox(height: 81.v, width: 86.h, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgProfileUser2, height: 80.adaptSize, width: 80.adaptSize, alignment: Alignment.centerLeft), CustomImageView(imagePath: ImageConstant.imgArrowDownSignToNavigate, height: 28.adaptSize, width: 28.adaptSize, alignment: Alignment.bottomRight)])), SizedBox(height: 22.v), _buildProfileUserTwoName(context), SizedBox(height: 15.v), _buildProfileUserTwoEmail(context), SizedBox(height: 15.v), _buildProfileUserTwoName1(context), SizedBox(height: 15.v), _buildCountry(context), SizedBox(height: 15.v), _buildCity(context), SizedBox(height: 15.v), _buildCityEditText1(context), SizedBox(height: 15.v), _buildFarmEditText(context), SizedBox(height: 5.v)]))), bottomNavigationBar: _buildCreateButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 55.v, leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 20.v, bottom: 16.v), onTap: () {onTapArrowOne(context);}), title: AppbarTitle(text: "lbl_create_profile".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 19.v))]); } 
/// Section Widget
Widget _buildProfileUserTwoName(BuildContext context) { return BlocSelector<CreateProfileBloc, CreateProfileState, TextEditingController?>(selector: (state) => state.profileUserTwoNameController, builder: (context, profileUserTwoNameController) {return CustomTextFormField(controller: profileUserTwoNameController, hintText: "lbl_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}); } 
/// Section Widget
Widget _buildProfileUserTwoEmail(BuildContext context) { return BlocSelector<CreateProfileBloc, CreateProfileState, TextEditingController?>(selector: (state) => state.profileUserTwoEmailController, builder: (context, profileUserTwoEmailController) {return CustomTextFormField(controller: profileUserTwoEmailController, hintText: "lbl_email".tr, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;});}); } 
/// Section Widget
Widget _buildProfileUserTwoName1(BuildContext context) { return BlocSelector<CreateProfileBloc, CreateProfileState, TextEditingController?>(selector: (state) => state.profileUserTwoNameController1, builder: (context, profileUserTwoNameController1) {return CustomTextFormField(controller: profileUserTwoNameController1, hintText: "lbl_farm_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}); } 
/// Section Widget
Widget _buildCountryEditText(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(right: 8.h), child: BlocSelector<CreateProfileBloc, CreateProfileState, TextEditingController?>(selector: (state) => state.countryEditTextController, builder: (context, countryEditTextController) {return CustomTextFormField(controller: countryEditTextController, hintText: "lbl_country".tr);}))); } 
/// Section Widget
Widget _buildStateEditText(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: BlocSelector<CreateProfileBloc, CreateProfileState, TextEditingController?>(selector: (state) => state.stateEditTextController, builder: (context, stateEditTextController) {return CustomTextFormField(controller: stateEditTextController, hintText: "lbl_state".tr);}))); } 
/// Section Widget
Widget _buildCountry(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildCountryEditText(context), _buildStateEditText(context)]); } 
/// Section Widget
Widget _buildCityEditText(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(right: 8.h), child: BlocSelector<CreateProfileBloc, CreateProfileState, TextEditingController?>(selector: (state) => state.cityEditTextController, builder: (context, cityEditTextController) {return CustomTextFormField(controller: cityEditTextController, hintText: "lbl_city".tr);}))); } 
/// Section Widget
Widget _buildVillageEditText(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: BlocSelector<CreateProfileBloc, CreateProfileState, TextEditingController?>(selector: (state) => state.villageEditTextController, builder: (context, villageEditTextController) {return CustomTextFormField(controller: villageEditTextController, hintText: "lbl_village".tr);}))); } 
/// Section Widget
Widget _buildCity(BuildContext context) { return Row(mainAxisAlignment: MainAxisAlignment.center, children: [_buildCityEditText(context), _buildVillageEditText(context)]); } 
/// Section Widget
Widget _buildCityEditText1(BuildContext context) { return BlocSelector<CreateProfileBloc, CreateProfileState, TextEditingController?>(selector: (state) => state.cityEditTextController1, builder: (context, cityEditTextController1) {return CustomTextFormField(controller: cityEditTextController1, hintText: "lbl_farm_capacity".tr);}); } 
/// Section Widget
Widget _buildFarmEditText(BuildContext context) { return BlocSelector<CreateProfileBloc, CreateProfileState, TextEditingController?>(selector: (state) => state.farmEditTextController, builder: (context, farmEditTextController) {return CustomTextFormField(controller: farmEditTextController, hintText: "lbl_farm".tr, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 22.v, 21.h, 21.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 17.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildCreateButton(BuildContext context) { return CustomElevatedButton(text: "lbl_create".tr, margin: EdgeInsets.only(left: 17.h, right: 17.h, bottom: 26.v), onPressed: () {onTapCreateButton(context);}); } 
/// Navigates to the homepageServiceBuyOneScreen when the action is triggered.
onTapArrowOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homepageServiceBuyOneScreen, ); } 

/// Displays a dialog with the [EditProfileDialog] content.
onTapCreateButton(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: EditProfileDialog.builder(context),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
 }
