import 'bloc/chick_feed_requirement_four_bloc.dart';import 'models/chick_feed_requirement_four_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class ChickFeedRequirementFourScreen extends StatelessWidget {const ChickFeedRequirementFourScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ChickFeedRequirementFourBloc>(create: (context) => ChickFeedRequirementFourBloc(ChickFeedRequirementFourState(chickFeedRequirementFourModelObj: ChickFeedRequirementFourModel()))..add(ChickFeedRequirementFourInitialEvent()), child: ChickFeedRequirementFourScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(16.h), child: Column(children: [BlocSelector<ChickFeedRequirementFourBloc, ChickFeedRequirementFourState, TextEditingController?>(selector: (state) => state.dayController, builder: (context, dayController) {return CustomTextFormField(controller: dayController, hintText: "lbl_day".tr, textInputAction: TextInputAction.done);}), SizedBox(height: 15.v), _buildBreed1(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildSave(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 19.v, bottom: 18.v)), title: AppbarTitle(text: "msg_chick_feed_requirement".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 20.v))]); } 
/// Section Widget
Widget _buildBreed1(BuildContext context) { return SizedBox(height: 207.v, width: 358.h, child: Stack(alignment: Alignment.center, children: [Padding(padding: EdgeInsets.only(bottom: 148.v), child: _buildFeedType(context, feedType: "lbl_breed".tr, menuImage: ImageConstant.imgMenu138, onTapMenu: () {onTapMenu(context);})), Padding(padding: EdgeInsets.symmetric(vertical: 74.v), child: _buildFeedType(context, feedType: "lbl_feed_type".tr, menuImage: ImageConstant.imgMenu136)), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 18.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Text("lbl_grams".tr, style: theme.textTheme.bodyMedium))), Align(alignment: Alignment.topRight, child: Container(height: 124.v, width: 118.h, margin: EdgeInsets.only(top: 37.v, right: 11.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgPolygon1, height: 14.v, width: 24.h, alignment: Alignment.topRight, margin: EdgeInsets.only(right: 7.h)), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_broiler".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 6.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_deshi".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 8.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_layer".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 7.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_breeder_farm".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 1.v)])))])))])); } 
/// Section Widget
Widget _buildSave(BuildContext context) { return CustomElevatedButton(text: "lbl_save".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 30.v)); } 
/// Common widget
Widget _buildFeedType(BuildContext context, {required String feedType, required String menuImage, Function? onTapMenu, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 16.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 5.v), child: Text(feedType, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.blueGray40001))), CustomImageView(imagePath: menuImage, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 4.v, right: 1.h, bottom: 3.v), onTap: () {onTapMenu!.call();})])); } 
/// Navigates to the chickFeedRequirementThreeScreen when the action is triggered.
onTapMenu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.chickFeedRequirementThreeScreen, ); } 
 }
