import 'bloc/terms_and_conditions_bloc.dart';import 'models/terms_and_conditions_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_icon_button.dart';import 'package:flutter/material.dart';class TermsAndConditionsScreen extends StatelessWidget {const TermsAndConditionsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<TermsAndConditionsBloc>(create: (context) => TermsAndConditionsBloc(TermsAndConditionsState(termsAndConditionsModelObj: TermsAndConditionsModel()))..add(TermsAndConditionsInitialEvent()), child: TermsAndConditionsScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<TermsAndConditionsBloc, TermsAndConditionsState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(height: 742.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(width: 358.h, margin: EdgeInsets.only(top: 22.v), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_1_acceptance_of2".tr, style: CustomTextStyles.labelMediumBlack900), TextSpan(text: "msg_by_accessing_or".tr, style: CustomTextStyles.bodySmallPoppins), TextSpan(text: "lbl_2_license".tr, style: CustomTextStyles.labelMediumBlack900), TextSpan(text: "msg_happy_poultry_farm2".tr, style: CustomTextStyles.bodySmallPoppins), TextSpan(text: "msg_3_user_content".tr, style: CustomTextStyles.labelMediumBlack900), TextSpan(text: "msg_you_understand_that".tr, style: CustomTextStyles.bodySmallPoppins), TextSpan(text: "lbl_4_disclaimer".tr, style: CustomTextStyles.labelMediumBlack900), TextSpan(text: "msg_the_happy_poultry".tr, style: CustomTextStyles.bodySmallPoppins), TextSpan(text: "msg_5_limitation_of".tr, style: CustomTextStyles.labelMediumBlack900), TextSpan(text: "msg_happy_poultry_farm3".tr, style: CustomTextStyles.bodySmallPoppins), TextSpan(text: "msg_6_indemnification".tr, style: CustomTextStyles.labelMediumBlack900), TextSpan(text: "msg_you_agree_to_indemnify".tr, style: CustomTextStyles.bodySmallPoppins), TextSpan(text: "msg_7_termination".tr, style: CustomTextStyles.labelMediumBlack900)]), textAlign: TextAlign.left))), _buildSettingsColumn(context)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 20.v, bottom: 17.v), onTap: () {onTapArrowOne(context);}), title: AppbarTitle(text: "msg_terms_and_conditions".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 20.v))]); } 
/// Section Widget
Widget _buildSettingsColumn(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 5.v), decoration: AppDecoration.outlineGray300, child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 10.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Padding(padding: EdgeInsets.only(right: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(10.h), decoration: IconButtonStyleHelper.fillPrimary, child: CustomImageView(imagePath: ImageConstant.imgNavBuySell)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(9.h), child: CustomImageView(imagePath: ImageConstant.imgNavBatches)))), Expanded(child: Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(11.h), child: CustomImageView(imagePath: ImageConstant.imgNavFeedManagement)))), Expanded(child: Padding(padding: EdgeInsets.only(left: 24.h), child: CustomIconButton(height: 44.adaptSize, width: 44.adaptSize, padding: EdgeInsets.all(11.h), child: CustomImageView(imagePath: ImageConstant.imgNavFarmSettings))))])), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 13.h, right: 3.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 11.v), child: Text("lbl_buy_sell".tr, style: theme.textTheme.bodySmall)), Spacer(flex: 37), Padding(padding: EdgeInsets.only(bottom: 11.v), child: Text("lbl_batches".tr, style: theme.textTheme.bodySmall)), Spacer(flex: 31), SizedBox(width: 58.h, child: Text("lbl_feed_management".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodySmall!.copyWith(height: 1.10))), Spacer(flex: 31), SizedBox(width: 37.h, child: Text("lbl_farm_settings".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodySmall!.copyWith(height: 1.10)))]))]))); } 
/// Navigates to the homepageServiceBuyOneScreen when the action is triggered.
onTapArrowOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homepageServiceBuyOneScreen, ); } 
 }
