import '../subscription_screen/widgets/poultrymarket_item_widget.dart';import 'bloc/subscription_bloc.dart';import 'models/poultrymarket_item_model.dart';import 'models/subscription_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';class SubscriptionScreen extends StatelessWidget {const SubscriptionScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SubscriptionBloc>(create: (context) => SubscriptionBloc(SubscriptionState(subscriptionModelObj: SubscriptionModel()))..add(SubscriptionInitialEvent()), child: SubscriptionScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 20.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgMdiCrown, height: 45.adaptSize, width: 45.adaptSize), SizedBox(height: 10.v), Text("msg_upgrade_to_premium".tr, style: CustomTextStyles.titleLargePoppinsBlack900), SizedBox(height: 46.v), _buildServices(context), SizedBox(height: 33.v), _buildDuration(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBuyNow(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 19.v, bottom: 18.v), onTap: () {onTapArrowOne(context);}), title: AppbarTitle(text: "lbl_subscription".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 12.v, 16.h, 21.v))]); } 
/// Section Widget
Widget _buildServices(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 8.v, bottom: 23.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 27.h), child: Text("lbl_services".tr, style: theme.textTheme.labelSmall))), SizedBox(height: 62.v), Text("msg_view_market_rates".tr, style: CustomTextStyles.bodySmallPoppins_1), SizedBox(height: 33.v), Text("lbl_sell_products".tr, style: CustomTextStyles.bodySmallPoppins_1), SizedBox(height: 24.v), SizedBox(width: 102.h, child: Text("msg_manage_your_broiler".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodySmallPoppins_1.copyWith(height: 1.40))), SizedBox(height: 30.v), Text("msg_manage_layer_farm".tr, style: CustomTextStyles.bodySmallPoppins_1)])), Expanded(child: SizedBox(height: 267.v, child: BlocSelector<SubscriptionBloc, SubscriptionState, SubscriptionModel?>(selector: (state) => state.subscriptionModelObj, builder: (context, subscriptionModelObj) {return ListView.separated(padding: EdgeInsets.only(left: 26.h), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 11.h);}, itemCount: subscriptionModelObj?.poultrymarketItemList.length ?? 0, itemBuilder: (context, index) {PoultrymarketItemModel model = subscriptionModelObj?.poultrymarketItemList[index] ?? PoultrymarketItemModel(); return PoultrymarketItemWidget(model);});})))])); } 
/// Section Widget
Widget _buildDuration(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 1.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: Container(margin: EdgeInsets.only(right: 5.h), padding: EdgeInsets.symmetric(horizontal: 28.h, vertical: 8.v), decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Align(alignment: Alignment.center, child: Text("lbl_1_month".tr, style: CustomTextStyles.labelLargeBlack900)), SizedBox(height: 2.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgTeenyiconsRupeeOutline, height: 10.adaptSize, width: 10.adaptSize, margin: EdgeInsets.only(top: 8.v, bottom: 17.v)), Text("lbl_99".tr, style: CustomTextStyles.headlineSmallBlack900)]), SizedBox(height: 1.v)]))), Expanded(child: Container(margin: EdgeInsets.symmetric(horizontal: 5.h), padding: EdgeInsets.symmetric(horizontal: 21.h, vertical: 9.v), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Align(alignment: Alignment.center, child: Text("lbl_6_months".tr, style: theme.textTheme.labelLarge)), SizedBox(height: 2.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgTwitter, height: 10.adaptSize, width: 10.adaptSize, margin: EdgeInsets.only(top: 8.v, bottom: 17.v)), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("lbl_299".tr, style: theme.textTheme.headlineSmall))]), SizedBox(height: 1.v)]))), Expanded(child: Container(margin: EdgeInsets.only(left: 5.h), padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 10.v), decoration: AppDecoration.outlineBluegray100.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Text("lbl_yearly".tr, style: theme.textTheme.labelLarge)), SizedBox(height: 36.v, width: 56.h, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.centerRight, child: Text("lbl_499".tr, style: theme.textTheme.headlineSmall)), CustomImageView(imagePath: ImageConstant.imgTwitter, height: 10.adaptSize, width: 10.adaptSize, alignment: Alignment.topLeft, margin: EdgeInsets.only(top: 8.v))]))])))])); } 
/// Section Widget
Widget _buildBuyNow(BuildContext context) { return CustomElevatedButton(text: "lbl_buy_now".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 29.v)); } 
/// Navigates to the homepageServiceBuyOneScreen when the action is triggered.
onTapArrowOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homepageServiceBuyOneScreen, ); } 
 }
