import 'bloc/batches_sub_user_two_bloc.dart';import 'models/batches_sub_user_two_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/core/utils/validation_functions.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class BatchesSubUserTwoScreen extends StatelessWidget {BatchesSubUserTwoScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<BatchesSubUserTwoBloc>(create: (context) => BatchesSubUserTwoBloc(BatchesSubUserTwoState(batchesSubUserTwoModelObj: BatchesSubUserTwoModel()))..add(BatchesSubUserTwoInitialEvent()), child: BatchesSubUserTwoScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 2.v), child: Column(children: [Text("lbl_add_sub_user".tr, style: CustomTextStyles.titleLargePoppinsBlack900SemiBold), SizedBox(height: 30.v), CustomImageView(imagePath: ImageConstant.imgProfileUser2, height: 80.adaptSize, width: 80.adaptSize, alignment: Alignment.centerLeft, margin: EdgeInsets.only(left: 132.h)), SizedBox(height: 30.v), _buildNameEditText(context), SizedBox(height: 15.v), _buildMobileNumberEditText(context), SizedBox(height: 15.v), _buildEditOnly(context), SizedBox(height: 5.v)]))), bottomNavigationBar: _buildAddButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 18.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_batch".tr, margin: EdgeInsets.only(left: 31.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 17.v))]); } 
/// Section Widget
Widget _buildNameEditText(BuildContext context) { return BlocSelector<BatchesSubUserTwoBloc, BatchesSubUserTwoState, TextEditingController?>(selector: (state) => state.nameEditTextController, builder: (context, nameEditTextController) {return CustomTextFormField(controller: nameEditTextController, hintText: "lbl_name".tr, validator: (value) {if (!isText(value)) {return "err_msg_please_enter_valid_text".tr;} return null;});}); } 
/// Section Widget
Widget _buildMobileNumberEditText(BuildContext context) { return BlocSelector<BatchesSubUserTwoBloc, BatchesSubUserTwoState, TextEditingController?>(selector: (state) => state.mobileNumberEditTextController, builder: (context, mobileNumberEditTextController) {return CustomTextFormField(controller: mobileNumberEditTextController, hintText: "msg_search_by_mobile".tr, textInputType: TextInputType.phone, validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;});}); } 
/// Section Widget
Widget _buildEditOnlyEditText(BuildContext context) { return BlocSelector<BatchesSubUserTwoBloc, BatchesSubUserTwoState, TextEditingController?>(selector: (state) => state.editOnlyEditTextController, builder: (context, editOnlyEditTextController) {return CustomTextFormField(width: 118.h, controller: editOnlyEditTextController, hintText: "lbl_edit_only".tr, textInputAction: TextInputAction.done, alignment: Alignment.bottomCenter, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 7.v));}); } 
/// Section Widget
Widget _buildEditOnly(BuildContext context) { return SizedBox(height: 77.v, width: 358.h, child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(bottom: 18.v), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 17.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v), child: Text("lbl_view_only".tr, style: theme.textTheme.bodyMedium)), CustomImageView(imagePath: ImageConstant.imgMenu138, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 3.v, right: 1.h, bottom: 2.v), onTap: () {onTapImgMenu(context);})]))), Align(alignment: Alignment.bottomRight, child: Container(height: 36.v, width: 118.h, margin: EdgeInsets.only(right: 12.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgPolygon1, height: 14.v, width: 24.h, alignment: Alignment.topRight, margin: EdgeInsets.only(right: 7.h)), _buildEditOnlyEditText(context)])))])); } 
/// Section Widget
Widget _buildAddButton(BuildContext context) { return CustomElevatedButton(text: "lbl_add".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 29.v)); } 
/// Navigates to the batchesSubUserOneScreen when the action is triggered.
onTapImgMenu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.batchesSubUserOneScreen, ); } 
 }
