import 'bloc/single_batch_vaccination_one_bloc.dart';import 'models/single_batch_vaccination_one_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class SingleBatchVaccinationOneScreen extends StatelessWidget {const SingleBatchVaccinationOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SingleBatchVaccinationOneBloc>(create: (context) => SingleBatchVaccinationOneBloc(SingleBatchVaccinationOneState(singleBatchVaccinationOneModelObj: SingleBatchVaccinationOneModel()))..add(SingleBatchVaccinationOneInitialEvent()), child: SingleBatchVaccinationOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 1.v), child: Column(children: [Text("lbl_add_vaccination".tr, style: CustomTextStyles.titleLargePoppinsBlack900SemiBold), SizedBox(height: 19.v), _buildAddVaccinationDate(context), SizedBox(height: 15.v), _buildVaccineTypeStack(context), SizedBox(height: 15.v), _buildMethodValue(context), SizedBox(height: 15.v), _buildDescriptionValue(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildAddButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 18.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_batch".tr, margin: EdgeInsets.only(left: 31.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 17.v))]); } 
/// Section Widget
Widget _buildAddVaccinationDate(BuildContext context) { return BlocSelector<SingleBatchVaccinationOneBloc, SingleBatchVaccinationOneState, TextEditingController?>(selector: (state) => state.addVaccinationDateController, builder: (context, addVaccinationDateController) {return CustomTextFormField(controller: addVaccinationDateController, hintText: "lbl_date".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 19.v, 21.h, 19.v), child: CustomImageView(imagePath: ImageConstant.imgVector, height: 18.v, width: 16.h)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildVaccineTypeStack(BuildContext context) { return SizedBox(height: 133.v, width: 358.h, child: Stack(alignment: Alignment.topCenter, children: [Padding(padding: EdgeInsets.only(top: 74.v), child: _buildVaccine(context, vaccineLabel: "lbl_vaccine_type2".tr, menuImage: ImageConstant.imgMenu136)), Padding(padding: EdgeInsets.only(bottom: 74.v), child: _buildVaccine(context, vaccineLabel: "lbl_vaccine".tr, menuImage: ImageConstant.imgMenu138, onTapMenu: () {onTapMenu(context);})), Align(alignment: Alignment.bottomRight, child: Container(height: 66.v, width: 118.h, margin: EdgeInsets.only(right: 12.h, bottom: 23.v), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgPolygon1, height: 14.v, width: 24.h, alignment: Alignment.topRight, margin: EdgeInsets.only(right: 7.h)), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 6.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_live".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 6.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_killed".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 1.v)])))])))])); } 
/// Section Widget
Widget _buildMethodValue(BuildContext context) { return BlocSelector<SingleBatchVaccinationOneBloc, SingleBatchVaccinationOneState, TextEditingController?>(selector: (state) => state.methodValueController, builder: (context, methodValueController) {return CustomTextFormField(controller: methodValueController, hintText: "lbl_method2".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 21.v, 22.h, 22.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildDescriptionValue(BuildContext context) { return BlocSelector<SingleBatchVaccinationOneBloc, SingleBatchVaccinationOneState, TextEditingController?>(selector: (state) => state.descriptionValueController, builder: (context, descriptionValueController) {return CustomTextFormField(controller: descriptionValueController, hintText: "lbl_description2".tr, textInputAction: TextInputAction.done);}); } 
/// Section Widget
Widget _buildAddButton(BuildContext context) { return CustomElevatedButton(text: "lbl_add".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 30.v)); } 
/// Common widget
Widget _buildVaccine(BuildContext context, {required String vaccineLabel, required String menuImage, Function? onTapMenu, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 18.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text(vaccineLabel, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.blueGray40001))), CustomImageView(imagePath: menuImage, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 2.v, right: 1.h), onTap: () {onTapMenu!.call();})])); } 
/// Navigates to the singleBatchVaccinationTwoScreen when the action is triggered.
onTapMenu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.singleBatchVaccinationTwoScreen, ); } 
 }
