import 'bloc/single_batch_vaccination_bloc.dart';import 'models/single_batch_vaccination_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class SingleBatchVaccinationScreen extends StatelessWidget {const SingleBatchVaccinationScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SingleBatchVaccinationBloc>(create: (context) => SingleBatchVaccinationBloc(SingleBatchVaccinationState(singleBatchVaccinationModelObj: SingleBatchVaccinationModel()))..add(SingleBatchVaccinationInitialEvent()), child: SingleBatchVaccinationScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 1.v), child: Column(children: [Text("lbl_add_vaccination".tr, style: CustomTextStyles.titleLargePoppinsBlack900SemiBold), SizedBox(height: 19.v), _buildAddVaccinationDate(context), SizedBox(height: 15.v), _buildAddVaccinationVaccineValue(context), SizedBox(height: 15.v), _buildAddVaccinationVaccineTypeValue(context), SizedBox(height: 15.v), _buildAddVaccinationMethod(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildAddButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 53.v, leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 18.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_batch".tr, margin: EdgeInsets.only(left: 31.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 17.v))]); } 
/// Section Widget
Widget _buildAddVaccinationDate(BuildContext context) { return BlocSelector<SingleBatchVaccinationBloc, SingleBatchVaccinationState, TextEditingController?>(selector: (state) => state.addVaccinationDateController, builder: (context, addVaccinationDateController) {return CustomTextFormField(controller: addVaccinationDateController, hintText: "lbl_date".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 19.v, 21.h, 19.v), child: CustomImageView(imagePath: ImageConstant.imgVector, height: 18.v, width: 16.h)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildAddVaccinationVaccineValue(BuildContext context) { return BlocSelector<SingleBatchVaccinationBloc, SingleBatchVaccinationState, TextEditingController?>(selector: (state) => state.addVaccinationVaccineValueController, builder: (context, addVaccinationVaccineValueController) {return CustomTextFormField(controller: addVaccinationVaccineValueController, hintText: "lbl_vaccine".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 23.v, 22.h, 20.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildAddVaccinationVaccineTypeValue(BuildContext context) { return BlocSelector<SingleBatchVaccinationBloc, SingleBatchVaccinationState, TextEditingController?>(selector: (state) => state.addVaccinationVaccineTypeValueController, builder: (context, addVaccinationVaccineTypeValueController) {return CustomTextFormField(controller: addVaccinationVaccineTypeValueController, hintText: "lbl_vaccine_type2".tr, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 23.v, 22.h, 19.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildAddVaccinationMethod(BuildContext context) { return SizedBox(height: 161.v, width: 358.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(bottom: 102.v), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 18.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("lbl_method2".tr, style: theme.textTheme.bodyMedium)), CustomImageView(imagePath: ImageConstant.imgMenu138, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 1.v, right: 1.h, bottom: 2.v), onTap: () {onTapImgMenu(context);})]))), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(bottom: 28.v), padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 16.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Text("lbl_description2".tr, style: theme.textTheme.bodyMedium)]))), Align(alignment: Alignment.bottomRight, child: Container(height: 124.v, width: 118.h, margin: EdgeInsets.only(right: 12.h), child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgPolygon1, height: 14.v, width: 24.h, alignment: Alignment.topRight, margin: EdgeInsets.only(right: 7.h)), Align(alignment: Alignment.bottomCenter, child: Container(padding: EdgeInsets.symmetric(vertical: 7.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_eye_drop".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 5.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_drinking_water".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 7.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_sc".tr, style: CustomTextStyles.bodySmall12)), SizedBox(height: 8.v), SizedBox(width: 118.h, child: Divider(color: appTheme.gray200)), SizedBox(height: 4.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_im".tr, style: CustomTextStyles.bodySmall12))])))])))])); } 
/// Section Widget
Widget _buildAddButton(BuildContext context) { return CustomElevatedButton(text: "lbl_add".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 30.v)); } 
/// Navigates to the singleBatchVaccinationTwoScreen when the action is triggered.
onTapImgMenu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.singleBatchVaccinationTwoScreen, ); } 
 }
