import 'bloc/login_bloc.dart';import 'models/login_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/core/utils/validation_functions.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class LoginScreen extends StatelessWidget {LoginScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<LoginBloc>(create: (context) => LoginBloc(LoginState(loginModelObj: LoginModel()))..add(LoginInitialEvent()), child: LoginScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 17.v), child: Column(children: [SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Container(width: 278.h, margin: EdgeInsets.only(left: 33.h, right: 48.h), child: Text("msg_welcome_back_glad".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.headlineLarge!.copyWith(height: 1.30)))), SizedBox(height: 58.v), BlocSelector<LoginBloc, LoginState, TextEditingController?>(selector: (state) => state.phoneNumberController, builder: (context, phoneNumberController) {return CustomTextFormField(controller: phoneNumberController, hintText: "lbl_phone_number".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.phone, validator: (value) {if (!isValidPhone(value)) {return "err_msg_please_enter_valid_phone_number".tr;} return null;});}), SizedBox(height: 49.v), CustomElevatedButton(text: "lbl_send_otp".tr, onPressed: () {onTapSendOTP(context);}), Spacer(flex: 39), _buildLoginWith(context), SizedBox(height: 20.v), _buildSocialButtons(context), Spacer(flex: 60), GestureDetector(onTap: () {onTapTxtDonthaveanaccount(context);}, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_don_t_have_an_account2".tr, style: CustomTextStyles.bodyMediumOnPrimary), TextSpan(text: "lbl_register_now".tr, style: CustomTextStyles.titleSmallBahnschriftPrimary)]), textAlign: TextAlign.left))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 389.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(22.h, 6.v, 326.h, 7.v), onTap: () {onTapArrowLeft(context);})); } 
/// Section Widget
Widget _buildLoginWith(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 7.v, bottom: 9.v), child: SizedBox(width: 117.h, child: Divider(color: appTheme.indigo50))), Text("lbl_or_login_with".tr, style: CustomTextStyles.titleSmallBahnschriftGray600), Padding(padding: EdgeInsets.only(top: 7.v, bottom: 9.v), child: SizedBox(width: 116.h, child: Divider(color: appTheme.indigo50)))])); } 
/// Section Widget
Widget _buildSocialButtons(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 8.h, right: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Container(height: 59.v, width: 105.h, padding: EdgeInsets.symmetric(horizontal: 37.h, vertical: 14.v), decoration: AppDecoration.outlineIndigo50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.imgFacebookIc, height: 27.adaptSize, width: 27.adaptSize, alignment: Alignment.center)), Container(height: 58.v, width: 110.h, padding: EdgeInsets.symmetric(horizontal: 37.h, vertical: 14.v), decoration: AppDecoration.outlineIndigo50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.imgGoogleIc, height: 27.adaptSize, width: 27.adaptSize, alignment: Alignment.centerLeft)), Container(height: 58.v, width: 110.h, padding: EdgeInsets.symmetric(horizontal: 37.h, vertical: 14.v), decoration: AppDecoration.outlineIndigo50.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: CustomImageView(imagePath: ImageConstant.imgCibApple, height: 27.adaptSize, width: 27.adaptSize, alignment: Alignment.centerLeft))])); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the otpVerificationTwoScreen when the action is triggered.
onTapSendOTP(BuildContext context) { NavigatorService.pushNamed(AppRoutes.otpVerificationTwoScreen, ); } 
/// Navigates to the registerScreen when the action is triggered.
onTapTxtDonthaveanaccount(BuildContext context) { NavigatorService.pushNamed(AppRoutes.registerScreen, ); } 
 }
