import 'bloc/otp_verification_two_bloc.dart';import 'models/otp_verification_two_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_pin_code_text_field.dart';import 'package:flutter/material.dart';class OtpVerificationTwoScreen extends StatelessWidget {const OtpVerificationTwoScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<OtpVerificationTwoBloc>(create: (context) => OtpVerificationTwoBloc(OtpVerificationTwoState(otpVerificationTwoModelObj: OtpVerificationTwoModel()))..add(OtpVerificationTwoInitialEvent()), child: OtpVerificationTwoScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 22.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 2.h), child: Text("msg_otp_verification".tr, style: theme.textTheme.headlineLarge))), SizedBox(height: 13.v), Align(alignment: Alignment.centerLeft, child: Container(width: 317.h, margin: EdgeInsets.only(left: 2.h, right: 30.h), child: Text("msg_enter_the_verification".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeBluegray400.copyWith(height: 1.50)))), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 2.h), child: BlocSelector<OtpVerificationTwoBloc, OtpVerificationTwoState, TextEditingController?>(selector: (state) => state.otpController, builder: (context, otpController) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});})), SizedBox(height: 39.v), CustomElevatedButton(text: "lbl_verify".tr, onPressed: () {onTapVerify(context);}), Spacer(), RichText(text: TextSpan(children: [TextSpan(text: "msg_didn_t_received2".tr, style: CustomTextStyles.bodyMediumOnPrimary), TextSpan(text: "lbl_resend".tr, style: CustomTextStyles.titleSmallBahnschriftPrimary)]), textAlign: TextAlign.left)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.fromLTRB(22.h, 6.v, 325.h, 6.v), onTap: () {onTapArrowLeft(context);})); } 

/// Navigates to the previous screen.
onTapArrowLeft(BuildContext context) { NavigatorService.goBack(); } 
/// Navigates to the homepageServiceBuyOneScreen when the action is triggered.
onTapVerify(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homepageServiceBuyOneScreen, ); } 
 }
