import 'bloc/vaccination_schedule_three_bloc.dart';import 'models/vaccination_schedule_three_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class VaccinationScheduleThreeScreen extends StatelessWidget {const VaccinationScheduleThreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<VaccinationScheduleThreeBloc>(create: (context) => VaccinationScheduleThreeBloc(VaccinationScheduleThreeState(vaccinationScheduleThreeModelObj: VaccinationScheduleThreeModel()))..add(VaccinationScheduleThreeInitialEvent()), child: VaccinationScheduleThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 18.v), child: Column(children: [_buildMenuForty(context), SizedBox(height: 15.v), _buildDay(context), SizedBox(height: 15.v), _buildMenuThirtySeven(context), SizedBox(height: 15.v), _buildGroup887(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildAdd(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 54.v, leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 19.v, bottom: 16.v)), title: AppbarTitle(text: "lbl_add_vaccination".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 18.v))]); } 
/// Section Widget
Widget _buildMenuForty(BuildContext context) { return BlocSelector<VaccinationScheduleThreeBloc, VaccinationScheduleThreeState, TextEditingController?>(selector: (state) => state.menuFortyController, builder: (context, menuFortyController) {return CustomTextFormField(controller: menuFortyController, hintText: "lbl_breed".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 21.v, 22.h, 21.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 58.v), contentPadding: EdgeInsets.only(left: 21.h, top: 19.v, bottom: 19.v));}); } 
/// Section Widget
Widget _buildDay(BuildContext context) { return BlocSelector<VaccinationScheduleThreeBloc, VaccinationScheduleThreeState, TextEditingController?>(selector: (state) => state.dayController, builder: (context, dayController) {return CustomTextFormField(controller: dayController, hintText: "lbl_day".tr);}); } 
/// Section Widget
Widget _buildMenuThirtySeven(BuildContext context) { return BlocSelector<VaccinationScheduleThreeBloc, VaccinationScheduleThreeState, TextEditingController?>(selector: (state) => state.menuThirtySevenController, builder: (context, menuThirtySevenController) {return CustomTextFormField(controller: menuThirtySevenController, hintText: "lbl_vaccine".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 23.v, 22.h, 20.v), child: CustomImageView(imagePath: ImageConstant.imgMenu136, height: 16.adaptSize, width: 16.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 59.v), contentPadding: EdgeInsets.only(left: 21.h, top: 20.v, bottom: 20.v));}); } 
/// Section Widget
Widget _buildGroup886(BuildContext context) { return BlocSelector<VaccinationScheduleThreeBloc, VaccinationScheduleThreeState, TextEditingController?>(selector: (state) => state.group886Controller, builder: (context, group886Controller) {return CustomTextFormField(width: 236.h, controller: group886Controller, hintText: "msg_newcastle_disease".tr, contentPadding: EdgeInsets.symmetric(horizontal: 12.h), borderDecoration: TextFormFieldStyleHelper.underLineGray, filled: false);}); } 
/// Section Widget
Widget _buildGroup892(BuildContext context) { return BlocSelector<VaccinationScheduleThreeBloc, VaccinationScheduleThreeState, TextEditingController?>(selector: (state) => state.group892Controller, builder: (context, group892Controller) {return CustomTextFormField(width: 236.h, controller: group892Controller, hintText: "msg_newcastle_disease2".tr, contentPadding: EdgeInsets.symmetric(horizontal: 12.h), borderDecoration: TextFormFieldStyleHelper.underLineGray, filled: false);}); } 
/// Section Widget
Widget _buildGroup896(BuildContext context) { return BlocSelector<VaccinationScheduleThreeBloc, VaccinationScheduleThreeState, TextEditingController?>(selector: (state) => state.group896Controller, builder: (context, group896Controller) {return CustomTextFormField(width: 236.h, controller: group896Controller, hintText: "msg_newcastle_disease3".tr, contentPadding: EdgeInsets.symmetric(horizontal: 12.h), borderDecoration: TextFormFieldStyleHelper.underLineGray, filled: false);}); } 
/// Section Widget
Widget _buildFowPoxvalue(BuildContext context) { return BlocSelector<VaccinationScheduleThreeBloc, VaccinationScheduleThreeState, TextEditingController?>(selector: (state) => state.fowPoxvalueController, builder: (context, fowPoxvalueController) {return CustomTextFormField(width: 236.h, controller: fowPoxvalueController, hintText: "lbl_fow_pox".tr, contentPadding: EdgeInsets.symmetric(horizontal: 12.h), borderDecoration: TextFormFieldStyleHelper.underLineGray, filled: false);}); } 
/// Section Widget
Widget _buildAvianInfectiousBronchitisvalue(BuildContext context) { return BlocSelector<VaccinationScheduleThreeBloc, VaccinationScheduleThreeState, TextEditingController?>(selector: (state) => state.avianInfectiousBronchitisvalueController, builder: (context, avianInfectiousBronchitisvalueController) {return CustomTextFormField(width: 236.h, controller: avianInfectiousBronchitisvalueController, hintText: "msg_avian_infectious".tr, contentPadding: EdgeInsets.symmetric(horizontal: 12.h), borderDecoration: TextFormFieldStyleHelper.underLineGray, filled: false);}); } 
/// Section Widget
Widget _buildMassachusettsTypeHStrainvalue(BuildContext context) { return BlocSelector<VaccinationScheduleThreeBloc, VaccinationScheduleThreeState, TextEditingController?>(selector: (state) => state.massachusettsTypeHStrainvalueController, builder: (context, massachusettsTypeHStrainvalueController) {return CustomTextFormField(width: 236.h, controller: massachusettsTypeHStrainvalueController, hintText: "msg_massachusetts_type".tr, contentPadding: EdgeInsets.symmetric(horizontal: 12.h), borderDecoration: TextFormFieldStyleHelper.underLineGray, filled: false);}); } 
/// Section Widget
Widget _buildInfectiousBursalDiseaseGaumbor(BuildContext context) { return BlocSelector<VaccinationScheduleThreeBloc, VaccinationScheduleThreeState, TextEditingController?>(selector: (state) => state.infectiousBursalDiseaseGaumborController, builder: (context, infectiousBursalDiseaseGaumborController) {return CustomTextFormField(width: 236.h, controller: infectiousBursalDiseaseGaumborController, hintText: "msg_infectious_bursal".tr, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 7.h), borderDecoration: TextFormFieldStyleHelper.underLineGray, filled: false);}); } 
/// Section Widget
Widget _buildGroup887(BuildContext context) { return SizedBox(height: 279.v, width: 358.h, child: Stack(alignment: Alignment.center, children: [Padding(padding: EdgeInsets.only(bottom: 220.v), child: _buildMethod(context, methodText: "lbl_vaccine_type2".tr, menuImage: ImageConstant.imgMenu138, onTapMenu: () {onTapMenu(context);})), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildMethod(context, methodText: "lbl_method2".tr, menuImage: ImageConstant.imgMenu136), SizedBox(height: 15.v), Container(width: 358.h, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 16.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Text("lbl_description2".tr, style: theme.textTheme.bodyMedium)]))])), Align(alignment: Alignment.bottomRight, child: Container(height: 241.v, width: 236.h, margin: EdgeInsets.only(right: 11.h), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgPolygon1, height: 14.v, width: 24.h, alignment: Alignment.topRight, margin: EdgeInsets.only(right: 7.h)), Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(vertical: 5.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.roundedBorder6), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 1.v), _buildGroup886(context), SizedBox(height: 5.v), _buildGroup892(context), SizedBox(height: 4.v), _buildGroup896(context), SizedBox(height: 4.v), _buildFowPoxvalue(context), SizedBox(height: 8.v), _buildAvianInfectiousBronchitisvalue(context), SizedBox(height: 7.v), _buildMassachusettsTypeHStrainvalue(context), SizedBox(height: 6.v), _buildInfectiousBursalDiseaseGaumbor(context), SizedBox(height: 6.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 12.h), child: Text("msg_newcastle_disease".tr, style: CustomTextStyles.bodySmall12)))])))])))])); } 
/// Section Widget
Widget _buildAdd(BuildContext context) { return CustomElevatedButton(text: "lbl_add".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 30.v)); } 
/// Common widget
Widget _buildMethod(BuildContext context, {required String methodText, required String menuImage, Function? onTapMenu, }) { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 18.v), decoration: AppDecoration.outlineIndigo.copyWith(borderRadius: BorderRadiusStyle.roundedBorder10), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text(methodText, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.blueGray40001))), CustomImageView(imagePath: menuImage, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 1.v, right: 1.h), onTap: () {onTapMenu!.call();})])); } 
/// Navigates to the vaccinationScheduleFourScreen when the action is triggered.
onTapMenu(BuildContext context) { NavigatorService.pushNamed(AppRoutes.vaccinationScheduleFourScreen, ); } 
 }
