import '../single_batch_view_income_page/widgets/userprofilelist_item_widget.dart';import 'bloc/single_batch_view_income_bloc.dart';import 'models/single_batch_view_income_model.dart';import 'models/userprofilelist_item_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_floating_button.dart';import 'package:basri_s_application4/widgets/custom_icon_button.dart';import 'package:basri_s_application4/widgets/custom_search_view.dart';import 'package:flutter/material.dart';class SingleBatchViewIncomePage extends StatelessWidget {const SingleBatchViewIncomePage({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SingleBatchViewIncomeBloc>(create: (context) => SingleBatchViewIncomeBloc(SingleBatchViewIncomeState(singleBatchViewIncomeModelObj: SingleBatchViewIncomeModel()))..add(SingleBatchViewIncomeInitialEvent()), child: SingleBatchViewIncomePage()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, margin: EdgeInsets.only(top: 1.v), child: Column(children: [Text("lbl_income".tr, style: CustomTextStyles.titleLargePoppinsBlack900SemiBold), SizedBox(height: 9.v), _buildSearchRow(context), SizedBox(height: 26.v), _buildUserProfileList(context)])), floatingActionButton: _buildFloatingActionButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 55.v, leadingWidth: 42.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 24.h, top: 20.v, bottom: 16.v), onTap: () {onTapArrowOne(context);}), title: AppbarTitle(text: "lbl_batch".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 13.v, 16.h, 19.v))]); } 
/// Section Widget
Widget _buildSearchRow(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 15.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: BlocSelector<SingleBatchViewIncomeBloc, SingleBatchViewIncomeState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_search_income".tr);})), Padding(padding: EdgeInsets.only(left: 13.h), child: CustomIconButton(height: 40.adaptSize, width: 40.adaptSize, padding: EdgeInsets.all(11.h), decoration: IconButtonStyleHelper.outlineIndigoTL6, child: CustomImageView(imagePath: ImageConstant.imgGroup401)))])); } 
/// Section Widget
Widget _buildUserProfileList(BuildContext context) { return BlocSelector<SingleBatchViewIncomeBloc, SingleBatchViewIncomeState, SingleBatchViewIncomeModel?>(selector: (state) => state.singleBatchViewIncomeModelObj, builder: (context, singleBatchViewIncomeModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 1.5.v), child: SizedBox(width: double.maxFinite, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray300)));}, itemCount: singleBatchViewIncomeModelObj?.userprofilelistItemList.length ?? 0, itemBuilder: (context, index) {UserprofilelistItemModel model = singleBatchViewIncomeModelObj?.userprofilelistItemList[index] ?? UserprofilelistItemModel(); return UserprofilelistItemWidget(model);});}); } 
/// Section Widget
Widget _buildFloatingActionButton(BuildContext context) { return CustomFloatingButton(height: 60, width: 60, backgroundColor: theme.colorScheme.primary, child: CustomImageView(imagePath: ImageConstant.imgMaterialSymbolsAdd, height: 30.0.v, width: 30.0.h)); } 
/// Navigates to the singleBatchRecordsTabContainerScreen when the action is triggered.
onTapArrowOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.singleBatchRecordsTabContainerScreen, ); } 
 }
