import '../currency_screen/widgets/currencylist_item_widget.dart';import 'bloc/currency_bloc.dart';import 'models/currency_model.dart';import 'models/currencylist_item_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_search_view.dart';import 'package:flutter/material.dart';class CurrencyScreen extends StatelessWidget {const CurrencyScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<CurrencyBloc>(create: (context) => CurrencyBloc(CurrencyState(currencyModelObj: CurrencyModel()))..add(CurrencyInitialEvent()), child: CurrencyScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 8.v), child: Column(children: [SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 16.h, right: 17.h), child: BlocSelector<CurrencyBloc, CurrencyState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "lbl_search_currency".tr);})), SizedBox(height: 14.v), Divider(), SizedBox(height: 8.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 27.h), child: Text("lbl_current".tr, style: theme.textTheme.bodyLarge))), SizedBox(height: 10.v), Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildCurrencyList(context), CustomImageView(imagePath: ImageConstant.imgGroup4, height: 397.v, width: 46.h, margin: EdgeInsets.only(left: 30.h))])])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 19.v, bottom: 18.v), onTap: () {onTapArrowOne(context);}), title: AppbarTitle(text: "lbl_currency".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 12.v, 16.h, 21.v))]); } 
/// Section Widget
Widget _buildCurrencyList(BuildContext context) { return BlocSelector<CurrencyBloc, CurrencyState, CurrencyModel?>(selector: (state) => state.currencyModelObj, builder: (context, currencyModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return Padding(padding: EdgeInsets.symmetric(vertical: 16.5.v), child: SizedBox(width: double.maxFinite, child: Divider(height: 1.v, thickness: 1.v, color: appTheme.gray300)));}, itemCount: currencyModelObj?.currencylistItemList.length ?? 0, itemBuilder: (context, index) {CurrencylistItemModel model = currencyModelObj?.currencylistItemList[index] ?? CurrencylistItemModel(); return CurrencylistItemWidget(model);});}); } 
/// Navigates to the farmSettingsScreen when the action is triggered.
onTapArrowOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.farmSettingsScreen, ); } 
 }
