import 'bloc/feed_type_three_bloc.dart';import 'models/feed_type_three_model.dart';import 'package:basri_s_application4/core/app_export.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_leading_image.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_title.dart';import 'package:basri_s_application4/widgets/app_bar/appbar_trailing_image.dart';import 'package:basri_s_application4/widgets/app_bar/custom_app_bar.dart';import 'package:basri_s_application4/widgets/custom_elevated_button.dart';import 'package:basri_s_application4/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';class FeedTypeThreeScreen extends StatelessWidget {const FeedTypeThreeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<FeedTypeThreeBloc>(create: (context) => FeedTypeThreeBloc(FeedTypeThreeState(feedTypeThreeModelObj: FeedTypeThreeModel()))..add(FeedTypeThreeInitialEvent()), child: FeedTypeThreeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 14.v), Padding(padding: EdgeInsets.symmetric(horizontal: 16.h), child: BlocSelector<FeedTypeThreeBloc, FeedTypeThreeState, TextEditingController?>(selector: (state) => state.feedTypeNameController, builder: (context, feedTypeNameController) {return CustomTextFormField(controller: feedTypeNameController, hintText: "lbl_feed_type".tr, textInputAction: TextInputAction.done);})), Spacer()])), bottomNavigationBar: _buildAddButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 37.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrow1, margin: EdgeInsets.only(left: 19.h, top: 18.v, bottom: 19.v)), title: AppbarTitle(text: "lbl_add_feed_type".tr, margin: EdgeInsets.only(left: 26.h)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgDots1, margin: EdgeInsets.fromLTRB(16.h, 12.v, 16.h, 21.v))]); } 
/// Section Widget
Widget _buildAddButton(BuildContext context) { return CustomElevatedButton(text: "lbl_add".tr, margin: EdgeInsets.only(left: 16.h, right: 16.h, bottom: 30.v), onPressed: () {onTapAddButton(context);}); } 
/// Navigates to the addOrderScreen when the action is triggered.
onTapAddButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.addOrderScreen, ); } 
 }
